### ISSUE TITLE
some question about .bin

### ISSUE THREAD

**Issue by peterrz** [mattjhayes/TP-Link-TL-1043ND-OpenvSwitch#1]
Hi,
i have Wr1043nd v3 i want build openvswitch but i get error image too big.
i wonder can i use .bin v2 in my router? instead v3 .

**Comment by mattjhayes** [comment]
Are you already running OpenWRT on it, or is this loading over the factory image?

**Comment by peterrz** [comment]
Im running openwrt on it ( i bulit it but miss some packages)
The project i want work on it have 1043nd.bin v2 but router v2 isn't availble anymore at store so i buy v3. now i want use .bin v2 on my router

**Comment by peterrz** [comment]
I have this problem with my openwrt compiled. 
i install openvswitch with this command opkg --force-depends install openvswitch
when i run command to build bridge i get this
ovs-vsctl add-br br0

Error detected while setting up 'br0'. See ovs-vswitchd log for details.
ovs-vswitchd log

2017-06-20T22:17:55Z|00001|ovs_numa|INFO|Discovered 0 NUMA nodes and 0 CPU cores
2017-06-20T22:17:55Z|00002|reconnect|INFO|log:
connecting...
2017-06-20T22:17:55Z|00003|reconnect|INFO|log: connection attempt failed (Address family not
supported by protocol)
and aslo when add port i get same error too. when i want brigde up ifconfig br0 up

ifconfig: SIOCGIFFLAGS: No such device
please guide me

**Comment by mattjhayes** [comment]
According to the OpenWRT wiki there aren't any hardware changes between v2 and v3 hardware: https://wikidevi.com/wiki/TP-LINK_TL-WR1043ND_v3.x

Are you loading the openwrt-ar71xx-generic-tl-wr1043nd-v3-squashfs-sysupgrade.bin image?
(note: the factory image is only for replacing the OEM on initial install of OpenWRT, I'll remove them from the repo at some stage to avoid confusion).

I'm currently writing build instructions (see http://nmeta.readthedocs.io/en/develop/userguide/build_a_lab.html), but haven't completed them yet. The configuration is the tricky part to get right, but I haven't documented that yet (but I do have a working config).

Hope this helps.

**Comment by peterrz** [comment]
Thanks to you. 
Yeah i use sysupgrade.bin . 
I have problem with my openvswitch, the size of this pakage is big every time i compiled it get me: >error too big to create image
 I see your instructions its greet. But i dont have this options in network/openvswitch
I have only openvswitch-ipsec and python 
I use 'git clone git://git.openwrt.org/15.05/openwrt.git'
' ./scripts/feeds install -a'
' ./scripts/feeds install -a'
Image build with kernel 3.18
When i use opkg isnatll give me error kernel version, then i should use opkg --force-depends install. 
Now i wnat build openvswitch bridge but it didnt create as i mentioned. Now im confused what should i do ?! 
Is this command true: ' ifconfig br0 up' ?!
I will be appreciated to answer me.

**Comment by mattjhayes** [comment]
If you're going to try and compile yourself then I suggest cloning from git clone https://github.com/openwrt/openwrt.git

Alternatively, just use the pre-compiled image I supplied - it includes Open vSwitch 2.7.0. No need to add the Open vSwitch package which has kernel dependency issues...

**Comment by peterrz** [comment]
Ok thanks to you. Now i have bigger problem i use wr1043ndv2 and makes my router brick.
It rebooting instantly

**Comment by mattjhayes** [comment]
I haven't had that before, here's link from OpenWRT site: https://wiki.openwrt.org/doc/howto/generic.debrick

Good luck...

**Comment by peterrz** [comment]
Thnaks i fix it with tftpd32
At site openwrt metion that rename recovery image to 'wr1043nv3_tp_recovery.bin'
But it isn't work, log file shows request for file <wr1043v3_tp_recovery.bin>  so funny 😄 i edit it.
There is trick in site for useing v2, need hex editor to modifi it. I do it and notify if it work.
I have problem with https://github.com/openwrt/openwrt.git
Cuase there is no kmod-crypto-core.
Now my question is:
how i can add ath9k.wireless debugging to your image and before final make add some code to debugging.? Is it possible?!

**Comment by mattjhayes** [comment]
Good to hear that you unbricked the router. Sorry, no idea re ath9k.wireless debugging - my experience with OpenWRT is limited to just this project.

I've updated build doc at http://nmeta.readthedocs.io/en/develop/userguide/build_a_lab.html#openwrt-with-open-vswitch - do a refresh in browser as tends to cache old pages.

Is it okay to close this issue? (i.e. does the image from this repo work on TP-Link? It works fine on my v2.1)

**Comment by peterrz** [comment]
Hi @mattjhayes. Yeah it's work fine . thanks for everything. I will check your link. Please close this
